[
	// Primaries
	["CUP_arifle_AK74", "CUP_arifle_AK74M", "CUP_arifle_AK74_GL", "CUP_arifle_AK74_GL_kobra",
	"CUP_arifle_AKS", "CUP_arifle_AKS_Gold",
	"CUP_arifle_AKS74", "CUP_arifle_AKS74_kobra", "CUP_arifle_AKS74_pso",
	"CUP_arifle_AKS74U", "CUP_arifle_AKS74UN_kobra_snds",
	"CUP_arifle_AK107", "CUP_arifle_AK107_kobra", "CUP_arifle_AK107_pso", "CUP_arifle_AK107_GL", "CUP_arifle_AK107_GL_kobra", "CUP_arifle_AK107_GL_pso",
	"CUP_arifle_AKM",
	"CUP_arifle_CZ805_A1", "CUP_arifle_CZ805_A1_Holo_Laser", "CUP_arifle_CZ805_A1_Aco_Laser", "CUP_arifle_CZ805_A1_MRCO_Laser", "CUP_arifle_CZ805_A1_ZDDot_Laser",
	"CUP_arifle_CZ805_GL", "CUP_arifle_CZ805_GL_Hamr_Laser", "CUP_arifle_CZ805_GL_ZDDot_Laser",
	"CUP_arifle_CZ805_A2", "CUP_arifle_CZ805_A2_Holo_Laser", "CUP_arifle_CZ805_A2_Aco_Laser", "CUP_arifle_CZ805_A2_ZDDot_Flashlight_Snds",
	"CUP_arifle_CZ805_B", "CUP_arifle_CZ805_B_GL", "CUP_arifle_CZ805B_GL_ACOG_Laser",
	"CUP_arifle_FNFAL", "CUP_arifle_FNFAL_railed",
	"CUP_arifle_G36A", "CUP_arifle_G36A_camo",
	"CUP_arifle_G36K", "CUP_arifle_G36K_camo",
	"CUP_arifle_G36C", "CUP_arifle_G36C_holo_snds", "CUP_arifle_G36C_camo", "CUP_arifle_G36C_camo_holo_snds",
	"CUP_arifle_L85A2_Holo_laser", "CUP_arifle_L85A2_SUSAT_Laser", "CUP_arifle_L85A2_ACOG_Laser", "CUP_arifle_L85A2_GL", "CUP_arifle_L85A2_GL_Holo_laser", "CUP_arifle_L85A2_GL_SUSAT_Laser", "CUP_arifle_L85A2_GL_ACOG_Laser",
	"CUP_arifle_M16A2", "CUP_arifle_M16A2_GL",
	"CUP_arifle_M16A4_Base", "CUP_arifle_M16A4_GL", "CUP_arifle_M16A4_Aim_Laser", "CUP_arifle_M16A4_ACOG_Laser", "CUP_arifle_M16A4_GL_Laser", "CUP_arifle_M16A4_GL_ACOG_Laser",
	"CUP_arifle_M4A1_BUIS_GL", "CUP_arifle_M4A1_BUIS_camo_GL", "CUP_arifle_M4A1_BUIS_desert_GL", "CUP_arifle_M4A1", "CUP_arifle_M4A1_camo", "CUP_arifle_M4A1_black", "CUP_arifle_M4A1_desert", "CUP_arifle_M4A1_camo_Aim", "CUP_arifle_M4A1_Aim", "CUP_arifle_M4A1_camo_AIM_snds", "CUP_arifle_M4A1_GL_Holo_Flashlight", "CUP_arifle_M4A1_GL_ACOG_Flashlight", "CUP_arifle_M4A1_camo_GL_Holo_Flashlight", "CUP_arifle_M4A1_camo_GL_Holo_Flashlight_Snds",
	"CUP_arifle_M4A3_desert", "CUP_arifle_M4A3_desert_Aim_Flashlight", "CUP_arifle_M4A3_desert_GL_ACOG_Laser",
	"CUP_arifle_Sa58P", "CUP_arifle_Sa58P_des",
	"CUP_arifle_Sa58V", "CUP_arifle_Sa58V_ACOG_Laser", "CUP_arifle_Sa58V_Aim_Laser", "CUP_arifle_Sa58V_camo",
	"CUP_arifle_Sa58RIS1", "CUP_arifle_Sa58RIS1_Aco_Laser", "CUP_arifle_Sa58RIS1_des", "CUP_arifle_Sa58RIS1_camo_Aco_Laser",
	"CUP_arifle_Sa58RIS2", "CUP_arifle_Sa58RIS2_Arco_Laser", "CUP_arifle_Sa58RIS2_gl", "CUP_arifle_Sa58RIS2_camo", "CUP_arifle_Sa58RIS2_camo_Arco_Laser",
	"CUP_arifle_Mk16_STD", "CUP_arifle_Mk16_STD_FG", "CUP_arifle_Mk16_STD_FG_Holo_Laser", "CUP_arifle_Mk16_STD_FG_LeupoldMk4CQT_Laser", "CUP_arifle_Mk16_STD_SFG", "CUP_arifle_Mk16_STD_EGLM", "CUP_arifle_Mk16_STD_EGLM_ACOG_Laser",
	"CUP_arifle_Mk16_CQC", "CUP_arifle_Mk16_CQC_FG", "CUP_arifle_Mk16_CQC_FG_Aim_Laser_snds", "CUP_arifle_Mk16_CQC_SFG", "CUP_arifle_Mk16_CQC_SFG_Holo", "CUP_arifle_Mk16_CQC_EGLM", "CUP_arifle_Mk16_CQC_EGLM_Holo_Laser_mfsup", "CUP_arifle_Mk16_SV",
	"CUP_arifle_Mk17_CQC", "CUP_arifle_Mk17_CQC_FG", "CUP_arifle_Mk17_CQC_SFG", "CUP_arifle_Mk17_CQC_EGLM",
	"CUP_arifle_Mk17_STD", "CUP_arifle_Mk17_STD_FG", "CUP_arifle_Mk17_STD_SFG", "CUP_arifle_Mk17_STD_EGLM", "CUP_arifle_Mk17_CQC_SFG_Aim_mfsup", "CUP_arifle_Mk17_STD_FG_Aim_Laser_snds", "CUP_arifle_Mk17_STD_EGL_ElcanSpecter_Laser",
	"CUP_arifle_Mk20", "CUP_arifle_Mk20_LeupoldMk4MRT", "CUP_arifle_Mk20_SB11420_snds",
	"CUP_arifle_XM8_Carbine", "CUP_arifle_XM8_Carbine_GL", "CUP_arifle_XM8_Carbine_FG",
	"CUP_arifle_xm8_sharpshooter",
	"CUP_arifle_XM8_Compact", "CUP_arifle_XM8_Compact_Rail", "CUP_arifle_XM8_Compact_Holo_Flashlight",
	"CUP_arifle_XM8_Railed", "CUP_arifle_XM8_Railed_ANPAS13c1_Laser", "CUP_arifle_XM8_Railed_Holo_Laser_snds",
	
	"CUP_RPK_74",
	"CUP_lmg_Pecheneg", "CUP_Pecheneg",
	"CUP_lmg_PKM", "CUP_PK",
	"CUP_lmg_UK59", "CUP_UK59_ACR",
	"CUP_arifle_L86A2", "CUP_arifle_L86A2_ACOG",
	"CUP_lmg_L110A1", "CUP_lmg_L110A1_Aim_Laser", "CUP_BAF_L110A1_Aim",
	"CUP_lmg_L7A2", "CUP_BAF_L7A2_GPMG",
	"CUP_arifle_MG36", "CUP_arifle_MG36_camo", "CUP_MG36", "CUP_MG36_camo",
	"CUP_lmg_M249_ElcanM145_Laser", "CUP_lmg_M249_Laser", "CUP_lmg_M249", "CUP_M249_m145_EP1", "CUP_M249_EP1", "CUP_M249",
	"CUP_lmg_M240", "CUP_lmg_M240_ElcanM143", "CUP_M240", "CUP_m240_scoped_EP1",
	"CUP_lmg_M60A4", "CUP_M60A4_EP1",
	"CUP_lmg_Mk48_des", "CUP_lmg_Mk48_wdl", "CUP_lmg_Mk48_des_Aim_Laser", "CUP_lmg_Mk48_wdl_Aim_Laser", "CUP_Mk_48_DES_EP1", "CUP_Mk_48",
	
	"CUP_srifle_AWM_des", "CUP_srifle_AWM_wdl", "CUP_srifle_AWM_des_SBPMII", "CUP_srifle_AWM_wdl_SBPMII",
	"CUP_srifle_CZ550", "CUP_huntingrifle",
	"CUP_srifle_CZ750", "CUP_srifle_CZ750_SOS_bipod", "CUP_CZ_750_S1_ACR",
	"CUP_srifle_DMR", "CUP_srifle_DMR_LeupoldMk4", "CUP_srifle_M14", "CUP_srifle_M14_Aim", "CUP_DMR", "CUP_M14_EP1",
	"CUP_srifle_M24_des", "CUP_srifle_M24_wdl", "CUP_srifle_M24_ghillie", "CUP_srifle_M24_des_LeupoldMk4LRT", "CUP_srifle_M24_wdl_LeupoldMk4LRT", "CUP_M24", "CUP_M24_des_EP1",
	"CUP_srifle_M40A3", "CUP_M40A3", 
	"CUP_srifle_M110",
	"CUP_SVD", "CUP_SVD_CAMO", "CUP_SVD_des_EP1", "CUP_srifle_SVD", "CUP_srifle_SVD_des", "CUP_srifle_SVD_des_ghillie_pso", "CUP_srifle_SVD_wdl_ghillie", "CUP_srifle_SVD_pso", "CUP_srifle_SVD_Des_pso",
	"CUP_srifle_VSSVintorez", "CUP_srifle_VSSVintorez_pso", "CUP_VSS_vintorez",
	"CUP_srifle_LeeEnfield", "CUP_LeeEnfield",
	"CUP_PMC_AS50_scoped",
	"CUP_ksvk",
	"CUP_M107"
	
	"CUP_AA12_PMC", "CUP_AA12_PMC",
	"CUP_M1014", "CUP_M1014",
	"CUP_Saiga12K", "CUP_Saiga12K",
	
	"CUP_smg_bizon", "CUP_smg_bizon_snds", "CUP_bizon", "CUP_bizon_silenced",
	"CUP_smg_bizon", "CUP_smg_bizon_snds", "CUP_bizon", "CUP_bizon_silenced",
	"CUP_smg_EVO", "CUP_smg_EVO_MRad_Flashlight", "CUP_smg_EVO_MRad_Flashlight_Snds", "CUP_Evo_mrad_ACR", "CUP_Evo_sd_ACR", "CUP_Evo_ACR", 
	"CUP_smg_EVO", "CUP_smg_EVO_MRad_Flashlight", "CUP_smg_EVO_MRad_Flashlight_Snds", "CUP_Evo_mrad_ACR", "CUP_Evo_sd_ACR", "CUP_Evo_ACR", 
	"CUP_smg_MP5SD6", "CUP_smg_MP5A5", "CUP_MP5SD", "CUP_MP5A5", 
	"CUP_smg_MP5SD6", "CUP_smg_MP5A5", "CUP_MP5SD", "CUP_MP5A5"
	],
	// Pistols
	["CUP_hgun_Colt1911", "CUP_hgun_Colt1911_snds", "CUP_Colt1911",
	"CUP_hgun_Compact", "CUP_hgun_Duty", "CUP_hgun_Duty_M3X", "CUP_hgun_Phantom", "CUP_hgun_Phantom_Flashlight", "CUP_hgun_Phantom_Flashlight_snds", "CUP_CZ_75_D_COMPACT", "CUP_CZ_75_P_07_DUTY", "CUP_CZ_75_SP_01_PHANTOM", "CUP_CZ_75_SP_01_PHANTOM_SD",
	"CUP_hgun_Glock17", "CUP_hgun_glock17_flashlight", "CUP_hgun_glock17_flashlight_snds", "CUP_hgun_glock17_snds", "CUP_Glock17_EP1",
	"CUP_hgun_M9", "CUP_hgun_M9_snds", "CUP_M9", "CUP_M9SD",
	"CUP_hgun_Makarov", "CUP_Makarov", "CUP_MakarovSD",
	"CUP_hgun_PB6P9", "CUP_hgun_PB6P9_snds",
	"CUP_hgun_SA61", "CUP_Sa61_EP1",
	"CUP_hgun_MicroUzi", "CUP_hgun_MicroUzi_snds", "CUP_UZI_EP1", "CUP_UZI_SD_EP1",
	"CUP_hgun_TaurusTracker455", "CUP_Revolver_EP1", "CUP_hgun_TaurusTracker455_gold", "CUP_Revolver_gold_EP1"
	],
	// Items
	["ItemGPS", "ItemGPS", "FirstAidKit", "FirstAidKit", "FirstAidKit", "FirstAidKit", "Medikit", "ToolKit"],
	// Launchers
	["CUP_launch_RPG18", "CUP_RPG18", "CUP_launch_M136", "CUP_M136"],
	// Consumables
	[["Land_CerealsBox_F", "isFood"], ["Land_Can_V1_F", "isDrink"], ["Land_Can_V2_F", "isDrink"], ["Land_TacticalBacon_F", "isFood"], ["Land_BakedBeans_F", "isFood"], ["Land_BottlePlastic_V2_F", "isDrink"], ["Land_Canteen_F", "isDrink"], ["Land_PowderedMilk_F", "isFood"], ["Land_RiceBox_F", "isFood"]]
]